### ISSUE TITLE
Crash with Dank Storage

### ISSUE THREAD

**Issue by jburrows82** [JayJay1989/BetterBedrockGenerator#1]
***Describe the bug***
Crashes with Dank Storage. It's probably to do with a known issue (found [here](https://github.com/Snownee/FruitTrees/issues/1)) that was easily solved.

**Logs/crashlogs/etc**
`[1;31m[11:24:15] [Render thread/FATAL] [mixin/]: Mixin apply failed betterbedrockgenerator.mixins.json:MixinFlattenBedrock -> net.minecraft.world.gen.NoiseChunkGenerator: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on makeBedrock could not find any targets matching 'makeBedrock' in net.minecraft.world.gen.NoiseChunkGenerator. Using refmap main.refmap.json [PREINJECT Applicator Phase -> betterbedrockgenerator.mixins.json:MixinFlattenBedrock -> Prepare Injections ->  -> handler$zza000$makeBedrock(Lnet/minecraft/world/chunk/IChunk;Ljava/util/Random;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on makeBedrock could not find any targets matching 'makeBedrock' in net.minecraft.world.gen.NoiseChunkGenerator. Using refmap main.refmap.json [PREINJECT Applicator Phase -> betterbedrockgenerator.mixins.json:MixinFlattenBedrock -> Prepare Injections ->  -> handler$zza000$makeBedrock(Lnet/minecraft/world/chunk/IChunk;Ljava/util/Random;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:543) ~[MixinBootstrap-1.0.1.jar:?] {}`

**Comment by JayJay1989** [comment]
i know, i think its impossible to do 2 mixins at a time. we need to wait for forge implementing itself.
And please use the template. Upload complete log to gist or pastebin

**Comment by JayJay1989** [comment]
Fixed in version 0.0.3
